# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-22 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexusercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certificate', to=settings.AUTH_USER_MODEL, verbose_name='用户-证书'),
        ),
        migrations.AlterUniqueTogether(
            name='cerficates',
            unique_together=set([('name', 'score')]),
        ),
    ]
