# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_auto_20180327_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexusercertificate',
            unique_together=set([('user', 'certificate')]),
        ),
    ]
