# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coefficient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientdetail',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='是否为特殊指定系数'),
        ),
    ]
