# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank13', '0001_initial'),
        ('coefficient', '0002_auto_20180327_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientdetail',
            name='rank13demands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Demands', verbose_name='岗位等级及岗位要求'),
        ),
        migrations.AlterField(
            model_name='coefficientdetail',
            name='rank13coefficent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Coefficent', verbose_name='系数'),
        ),
    ]
