# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coefficient', '0003_auto_20180327_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficientdetail',
            name='coefficent',
            field=models.FloatField(default=0, help_text='系数', verbose_name='系数'),
        ),
        migrations.AlterField(
            model_name='coefficientdetail',
            name='rank13coefficent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Coefficent', verbose_name='等级行员关联系数'),
        ),
    ]
