# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 15:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coefficient', '0004_auto_20180329_0958'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coefficientdetail',
            unique_together=set([('user', 'coefficent')]),
        ),
    ]
