# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='大庆农商银行', help_text='组织', max_length=30, verbose_name='组织')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='岗位', max_length=30, verbose_name='岗位')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='Rank13Coefficent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, help_text='等次', verbose_name='等次')),
                ('level', models.IntegerField(default=1, help_text='级次', verbose_name='级次')),
                ('coefficent', models.DecimalField(decimal_places=2, default=0, help_text='系数', max_digits=4, verbose_name='系数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('agent', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='rank13.Agent', verbose_name='组织')),
                ('post', models.ForeignKey(help_text='岗位', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='rank13.Post', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '行员等级对应岗位系数',
                'verbose_name_plural': '行员等级对应岗位系数',
            },
        ),
    ]
