# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank13', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='大庆农商银行', help_text='组织', max_length=30, unique=True, verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='', help_text='岗位', max_length=30, unique=True, verbose_name='岗位'),
        ),
    ]
