# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-27 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank13', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rank13demands',
            unique_together=set([('rank', 'level')]),
        ),
    ]
