# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank13', '0002_auto_20180323_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank13Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, help_text='等次', verbose_name='等次')),
                ('level', models.IntegerField(default=1, help_text='级次', verbose_name='级次')),
                ('demandyears', models.IntegerField(default=1, help_text='金融从业年限要求', verbose_name='金融从业年限要求')),
                ('educationdemands', models.IntegerField(choices=[(1, '中专、高中及以下'), (2, '专科'), (3, '本科'), (4, '硕士研究生'), (5, '博士'), (6, '教授')], default=1, help_text='学历: 1(本科),2(中专、高中及以下),3(专科),4(硕士研究生),5(博士),6(教授)', verbose_name='学历')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('agent', models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='agent_demand', to='rank13.Agent', verbose_name='组织')),
                ('post', models.ForeignKey(help_text='岗位', on_delete=django.db.models.deletion.CASCADE, related_name='post_demand', to='rank13.Post', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '行员等级对应岗位系数',
                'verbose_name_plural': '行员等级对应岗位系数',
            },
        ),
        migrations.AlterField(
            model_name='rank13coefficent',
            name='agent',
            field=models.ForeignKey(help_text='组织', on_delete=django.db.models.deletion.CASCADE, related_name='agent_rank13coefficent', to='rank13.Agent', verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='rank13coefficent',
            name='post',
            field=models.ForeignKey(help_text='岗位', on_delete=django.db.models.deletion.CASCADE, related_name='post_rank13coefficent', to='rank13.Post', verbose_name='岗位'),
        ),
    ]
