# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank13',
            field=models.ForeignKey(help_text='行员等级(共13等)', on_delete=django.db.models.deletion.CASCADE, to='rank13.Rank13Coefficent', verbose_name='行员等级'),
        ),
    ]
