# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cmanagerrank',
            field=models.IntegerField(choices=[(1, '无'), (2, '初级'), (3, '中级'), (4, '高级'), (5, '资深')], default=1, help_text='客户经理级次: 1(无),2(初级),3(中级),4(高级),5(资深)', verbose_name='客户经理级次'),
        ),
    ]
