# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 12:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0003_auto_20180327_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexuserdepart',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
