# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_indexuserdepart_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexuserdepart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_depart', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户-部门'),
        ),
    ]
