# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0006_auto_20180329_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departdetail',
            name='basesalary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
